{
 "title": "Discovergy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "meter",
    "label": "Meter ID",
    "query": {
     "query": "label_values(discovergy_ampere_phase2, meterId)\t"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "expr": "discovergy_ampere_phase1{meterId=\"$meter\"}",
     "legendFormat": "Phase 1"
    },
    {
     "expr": "discovergy_ampere_phase2{meterId=\"$meter\"}",
     "legendFormat": "Phase 2"
    },
    {
     "expr": "discovergy_ampere_phase3{meterId=\"$meter\"}",
     "legendFormat": "Phase 3"
    }
   ]
  },
  {
   "title": "P1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discovergy_ampere_phase1{meterId=\"$meter\"}"
    }
   ]
  },
  {
   "title": "P2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discovergy_ampere_phase2{meterId=\"$meter\"}"
    }
   ]
  },
  {
   "title": "P3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discovergy_ampere_phase3{meterId=\"$meter\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "yaxes": [
    { "format": "mvolt" }
   ],
   "targets": [
    {
     "expr": "discovergy_voltage_phase1{meterId=\"$meter\"}",
     "legendFormat": "Phase 1"
    },
    {
     "expr": "discovergy_voltage_phase2{meterId=\"$meter\"}",
     "legendFormat": "Phase 2"
    },
    {
     "expr": "discovergy_voltage_phase3{meterId=\"$meter\"}",
     "legendFormat": "Phase 3"
    }
   ]
  },
  {
   "title": "P1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discovergy_voltage_phase1{meterId=\"$meter\"}"
    }
   ]
  },
  {
   "title": "P2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discovergy_voltage_phase2{meterId=\"$meter\"}"
    }
   ]
  },
  {
   "title": "P3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discovergy_voltage_phase1{meterId=\"$meter\"}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "discovergy_milliwatt_phase1{meterId=\"$meter\"}",
     "legendFormat": "Phase 1"
    },
    {
     "expr": "discovergy_milliwatt_phase2{meterId=\"$meter\"}",
     "legendFormat": "Phase 2"
    },
    {
     "expr": "discovergy_milliwatt_phase3{meterId=\"$meter\"}",
     "legendFormat": "Phase 3"
    }
   ]
  }
 ]
}